# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    # domain (not used)
    domain: 'http://127.0.0.1:8000'
    # upload dir
    upload_directory: '%kernel.project_dir%/public/u'
    # how many items to display in /files and /pastes
    number_of_items: 27
    # allowed filetypes (single comma seperated string, no spaces, remove exe and dll if running on windows)
    allowed_filetypes: >-
     application/x-photoshop,
     application/psd,
     application/photoshop,
     application/vnd.android.package-archive,
     application/pdf,
     application/octet-stream,
     application/java-archive,
     font/ttf,
     font/otf,
     font/woff,
     font/woff2,
     font/sfnt,
     image/png,
     image/vnd.adobe.photoshop,
     image/psd,
     image/jpg,
     image/jpeg,
     image/tiff,
     image/gif,
     image/svg,
     image/svg+xml,
     text/plain,
     application/x-font-ttf,
     application/font-otf,
     application/otf,
     application/font,
     applicatoin/vnd.ms-opentype,
     application/epub+zip,
     application/vnd.ms-powerpoint,
     application/x-dosexec,
     application/vnd.openxmlformats-officedocument.presentationml.presentation,
     application/vnd.openxmlformats-officedocument.presentationml.presentation,
     application/vnd.oasis.opendocument.text,
     application/vnd.oasis.opendocument.presentation,
     application/msword,
     application/vnd.openxmlformats-officedocument.wordprocessingml.document,
     application/vnd.ms-excel,
     application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
     application/x-tar,
     application/x-gzip,
     application/x-bzip2,
     application/x-xz,
     application/x-7z-compressed,
     application/zip,
     audio/x-flac,
     audio/opus,
     audio/webm,
     audio/flac,
     audio/mpeg,
     video/webm,
     video/mp4,
     video/x-matroska,
     video/quicktime


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
